name: CI

on:
  push:
    branches: [master,develop,refactor/v3]
  pull_request:
    branches: [master,develop]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Eslint check
        run: yarn lint
      - name: Type check
        run: yarn tsc

  test:
    name: Unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Test
        run: yarn test
      - name: Codecov upload
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Building
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build
