name: CI

on:
  push:
    branches: [master,develop,refactor/v3]
  pull_request:
    branches: [master,develop]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: yarn install
      - name: Eslint check
        run: yarn lint

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: yarn install
      - name: Test
        run: yarn test --forceExit
      - name: Codecov upload
        uses: codecov/codecov-action@v3.1.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build
