name: CI

on:
  push:
    branches: [master,develop]
  pull_request:
    branches: [master,develop]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install deps
        run: yarn install
      - name: Eslint check
        run: yarn lint

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps
        run: yarn install
      - name: Test
        run: yarn test
      - name: Codecov upload
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build
